name: sw_badge
description: A Flutter widget to create Badges

version: 1.0.0
author: luizeof <luizeof@gmail.com>
homepage: https://github.com/luizeof/flutter-badge-widget

environment:
  sdk: ">=1.20.1 <3.0.0"
  flutter: ">=0.1.4 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
